export default {
  ONBOARDING: 'ONBOARDING',
  TAB_NAVIGATOR: 'TAB_NAVIGATOR',
  SEARCH_RESULTS: 'SEARCH_RESULTS',
  ERROR_SCREEN: 'ERROR_SCREEN',
  SEARCH: 'SEARCH',
  FAVORITES: 'FAVORITES',
  PROPERTY_SCREEN: 'PROPERTY_SCREEN',
};
